### ISSUE TITLE
Can files generated by this plugin be modified with other external tools？

### ISSUE THREAD

**Issue by Irisjuju** [antoniotejada/obsidian-edit-history#20]
Hello, thank you for developing this plugin.This is not really an issue, it is more of a question: can the md.edtz files generated by the plugin be edited with external tools?（So sad that i have no clue about coding things） I would greatly appreciate your answer. 
I use obsidian to write novels, but mostly for my own enjoyment and not on public platforms. I worry that if I publish later, someone else may have already had similar ideas. For fear that I can't explain it that i didn't copy anyone, I am looking for Something can prove it. If the Edit History files can't be edited externally, It would be a solid proof of when my idea created. Looking forward to your response.   Best regards.

**Comment by Irisjuju** [comment]
never mind,i changed the file extension from .edtz to .zip ,then extract them and find they can be edited.got the answer.

**Comment by antoniotejada** [comment]
Right, everything is done using standard tools, zip file and patch format inside the zip, but even if it didn't it would be a very weak proof since the plugin is opensource and you could use this plugin to generate any edtz file with any timestamps.

One thing you can do is to backup the edtz file somewhere that does timestamping or keeps revisions (AWS S3 comes to mind, probably any cloud backup service), but at that point you could also backup your file instead and forget the edtz file.
